### ISSUE TITLE
Cannot install with setup.py in Window Anaconda 

### ISSUE THREAD

**Issue by TharHtetAungg** [ShirleyMaxx/VirtualMarker#10]
Hello, I have an error when I install setup.py in window (Anaconda). 

And also I have another two questions. 
-Do you have google colab for this code? 
-This model can output 3D obj ? 

![image](https://github.com/ShirleyMaxx/VirtualMarker/assets/79152768/aedcecfa-cc26-433e-90b5-fad1deee078d)

Thanks.

**Comment by EverRaynor** [comment]
in line 19, add encoding "utf-8" param.

**Comment by ShirleyMaxx** [comment]
> Do you have google colab for this code?

Sorry for that, we do not provide the google colab at this time.

> This model can output 3D obj ?

Yes! We have a function that could save a 3D obj file defined as [`save_obj`](https://github.com/ShirleyMaxx/VirtualMarker/blob/60dbbe404b2665fdd8b4fe17a308f171f692c107/virtualmarker/utils/funcs_utils.py#L57C7-L57C7) in `virtualmarker/utils/funcs_utils.py`. The usage can be referred to [here](https://github.com/ShirleyMaxx/VirtualMarker/blob/60dbbe404b2665fdd8b4fe17a308f171f692c107/virtualmarker/dataset/joints_dataset.py#L403). Or you can set `cfg.test.save_obj` as `True` when evaluating the models, and the `.obj` file will be saved in the experimental folder.

**Comment by TharHtetAungg** [comment]
Thank you !
