### ISSUE TITLE
Input_results_in_2d.mp4 is same as input.mp4

### ISSUE THREAD

**Issue by alexinnovap** [ShirleyMaxx/VirtualMarker#12]
Hi,

After running baseline.sh, the experiment folder was created with the resultant video. This video is exactly the same as the input video with no keyframes or mesh on the human doing the side monster walk action.

Could you help me out.

Thank you!

**Comment by ShirleyMaxx** [comment]
Hi, sorry for the late reply. Have you figured out the problems?

**Comment by alexinnovap** [comment]
Yes, i incorrectly installed the Render Env. Now it is working.

**Comment by sebastianopazo1** [comment]
Hi! How did you installed the render env. correctly? I tried following the instructions but still no results.
Thanks for your help!
