### ISSUE TITLE
output problem

### ISSUE THREAD

**Issue by jack121388** [ShirleyMaxx/VirtualMarker#15]
I want to know. Can the identified model be output? I mean, suppose I pose a pose, and then he can output a 3D model file, which I can use on the 3D engine.

**Comment by ShirleyMaxx** [comment]
Hi, if I understand correctly, you mean given the SMPL pose and shape parameters, could we output the 3D mesh model?

Yes, once we get the 6890 vertices 3D positions, we could output the mesh in `.obj` format by using the function `save_obj` [here](https://github.com/ShirleyMaxx/VirtualMarker/blob/master/virtualmarker/utils/funcs_utils.py#L57). The usage is below or please refer to [here](https://github.com/ShirleyMaxx/VirtualMarker/blob/master/virtualmarker/dataset/joints_dataset.py#L403).

```python
save_obj(mesh_verts, smpl_faces, 'output.obj')
# mesh_verts (6890, 3)
# smpl_faces could be obtained from the SMPL layer
# 'output.obj' is the saved file name
```

Once the `.obj` is saved, you could open it using 3D engines such as Blender or MeshLab.
