### ISSUE TITLE
Images deleted after inference

### ISSUE THREAD

**Issue by biansy000** [ShirleyMaxx/VirtualMarker#16]
Hello, thank you for sharing your impressive work. But I meet a problem where all my inference images were deleted by the inference code due to the following line of code:

https://github.com/ShirleyMaxx/VirtualMarker/blob/60dbbe404b2665fdd8b4fe17a308f171f692c107/main/inference.py#L293

The code deletes the parent path of 'input_path' if the last folder name of my 'input_path' has less than four words, and it caused me much trouble.  It would be better if the author could consider changing this line of code.

**Comment by ShirleyMaxx** [comment]
Hi, I feel so sorry for the trouble and have commented all the `shutil.rmtree` in the `inference.py`. Apologize again.
