### ISSUE TITLE
Missing configuration file

### ISSUE THREAD

**Issue by xiaoTan12** [ShirleyMaxx/VirtualMarker#20]
Traceback (most recent call last):
  File "main/inference.py", line 355, in <module>
    main(args)
  File "main/inference.py", line 337, in main
    detection_all, max_person, valid_frame_idx_all = detect_all_persons(args, img_dir)
  File "main/inference.py", line 226, in detect_all_persons
    det_update_config(f'{virtualpose_name}/configs/images/images_inference.yaml')
  File "/data/tx/VirtualPose/virtualpose/core/config.py", line 224, in update_config
    with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'VirtualPose/configs/images/images_inference.yaml'
I ran into this problem at runtime please what can I do to fix it?

**Comment by ShirleyMaxx** [comment]
Hi, It seems like the error is indicating that [VirtualPose](https://github.com/wkom/VirtualPose/tree/main) hasn't been cloned and installed correctly. Please refer to the [QuickDemo](https://github.com/ShirleyMaxx/VirtualMarker?tab=readme-ov-file#quick-demo-star) section in the readme to ensure VirtualPose is installed properly.

**Comment by xiaoTan12** [comment]
Already solved, thank you very much
