### ISSUE TITLE
pyrender is not correctly imported

### ISSUE THREAD

**Issue by tharuneshwar-s** [ShirleyMaxx/VirtualMarker#25]
Hello Community,

I installed ```pip install pyrender```

```
sh command/simple3dmesh_infer/baseline.sh
```

![Screenshot from 2024-02-15 05-24-48](https://github.com/ShirleyMaxx/VirtualMarker/assets/84437531/03aab012-bc95-453e-a42b-b1e00806d53c)

How to resolve this error??

**Comment by ShirleyMaxx** [comment]
Hi, this error indicates that pyrender hasn't been installed correctly. Please refer to the instructions for installing pyrender provided in the [QuickDemo](https://github.com/ShirleyMaxx/VirtualMarker/tree/master?tab=readme-ov-file#quick-demo-star) section.

**Comment by LiuJinzhe-Keepgoing** [comment]
@THARUNESHWAR-369 
Hello, I also encountered the same problem: pyrender is not correctly imported., 
but it still cannot be solved smoothly according to the quick boot method. Do you have any good solutions?
