### ISSUE TITLE
data processing scripts

### ISSUE THREAD

**Issue by HaozhouPang** [ShirleyMaxx/VirtualMarker#3]
Hello, thanks for posting this work!

I was wondering can you share the script that you used to process the surreal data from the original .mat files to the pkl anotation file that you included in the project.

Much appreciated

**Comment by ShirleyMaxx** [comment]
Hi, thanks for your interest!

The `.pkl` file is actually processed from the `.json` file provided by [Pose2Mesh](https://github.com/hongsukchoi/Pose2Mesh_RELEASE#data) as you could see in our [`surreal.py`](https://github.com/ShirleyMaxx/VirtualMarker/blob/master/lib/dataset/surreal.py#L46). However, we could not know how to get `.json` file from the original `.mat` file. Maybe you could refer to this [issue](https://github.com/hongsukchoi/Pose2Mesh_RELEASE/issues/35).

Hope this could help.

**Comment by HaozhouPang** [comment]
Hello @ShirleyMaxx ,

Thank you for the links and the clarifications. 

Best.

**Comment by HaozhouPang** [comment]
The author of Pose2Mesh has posted the data parsing code, for those who are interested, please check: 

https://github.com/mks0601/I2L-MeshNet_RELEASE/tree/master/tool/SURREAL
