### ISSUE TITLE
could you provide assets with more markers?

### ISSUE THREAD

**Issue by YongtaoGE** [ShirleyMaxx/VirtualMarker#6]
Hi, thanks for the great work. I found the files in the assets folder only provide 64 markers, which remove the markers on the head. It is appreciated if you can provide markers with 96 points mentioned in the paper.

Thanks very much.

**Comment by ShirleyMaxx** [comment]
Hi, thanks for your interest. 

More configs `K=16, 32, 96` of the learned virtual markers can be found [here](https://pkueducn-my.sharepoint.com/:f:/g/personal/maxiaoxuan_pku_edu_cn/Et4c8-wc0CBCh--jrd8TdmUB3zwI8ab95JY9gfkmtvyOmA?e=IY70pA).

**Comment by YongtaoGE** [comment]
@ShirleyMaxx, Thanks again for your help!
