### ISSUE TITLE
Invalid links

### ISSUE THREAD

**Issue by ssssholmes** [ShirleyMaxx/VirtualMarker#8]
Hi, thanks for your great work. The data annotation link and some other links seem invalid and I cannot open them. @ShirleyMaxx

**Comment by ShirleyMaxx** [comment]
Hi, thank you for your interest. The old link is broken as the account was migrated by our school. The good news is that we have updated all the links and it is now available again. We apologize for any inconvenience this may have caused and invite you to visit the new links.
